#include "turtle_gui.hpp"
#include <imgui/imgui.h>
#include "heap_monitor.hpp"

namespace turtlepreter {
TurtleGUI::TurtleGUI(Controllable* c,Interpreter* i):m_controllable(c),m_interpreter(i),m_widthLeftPanel(250){}
void TurtleGUI::build() { ImGuiIO& io=ImGui::GetIO(); ImGui::SetNextWindowPos({0,0}); ImGui::SetNextWindowSize(io.DisplaySize); ImGui::Begin("TP",nullptr,ImGuiWindowFlags_NoResize|ImGuiWindowFlags_NoMove|ImGuiWindowFlags_NoCollapse); buildTopBar();ImGui::Separator();buildLeftPanel();ImGui::SameLine();buildSplitter();ImGui::SameLine();buildRightPanel(); ImGui::End(); }
void TurtleGUI::buildTopBar(){ ImGui::BeginDisabled(m_interpreter->isFinished()); if(ImGui::Button("Run", {100,0}))m_interpreter->interpretAll(*m_controllable); ImGui::EndDisabled();ImGui::SameLine(); ImGui::BeginDisabled(m_interpreter->isFinished()); if(ImGui::Button("Step",{100,0}))m_interpreter->interpretStep(*m_controllable); ImGui::EndDisabled();ImGui::SameLine(); ImGui::BeginDisabled(!m_interpreter->wasSomethingExecuted()&&m_interpreter->getCurrent()==m_interpreter->getRoot()); if(ImGui::Button("Reset",{100,0})){m_controllable->reset();m_interpreter->reset();} ImGui::EndDisabled();ImGui::SameLine(); ImGui::BeginDisabled(m_interpreter->isFinished()); bool s=m_interpreter->stopOnNodeWithoutCommand(); if(ImGui::Checkbox("Stop on no-cmd",&s))m_interpreter->setStopOnNodeWithoutCommand(s); ImGui::EndDisabled(); }
void TurtleGUI::buildLeftPanel(){ImGui::BeginChild("Script", {m_widthLeftPanel,0},true);populateTreeNodes(m_interpreter->getRoot());ImGui::EndChild();}
void TurtleGUI::buildSplitter(){ImGui::PushStyleColor(ImGuiCol_Button,{.5f,.5f,.5f,1});ImGui::PushStyleColor(ImGuiCol_ButtonHovered,{.7f,.7f,.7f,1});ImGui::PushStyleColor(ImGuiCol_ButtonActive,{.9f,.9f,.9f,1});ImGui::Button("|",{5,ImGui::GetContentRegionAvail().y});if(ImGui::IsItemActive()){m_widthLeftPanel+=ImGui::GetIO().MouseDelta.x;if(m_widthLeftPanel<100)m_widthLeftPanel=100;}ImGui::PopStyleColor(3);}
void TurtleGUI::buildRightPanel(){ImGui::BeginChild("Turtle",{0,0},true);auto* dl=ImGui::GetWindowDrawList();auto r=friimgui::Region::createFromAvail();dl->AddRectFilled(r.getP0(),r.getP2(),IM_COL32(60,60,60,255));r.reserveSpace();m_controllable->draw(r);ImGui::EndChild();}
void TurtleGUI::populateTreeNodes(Node* n){if(n){ImGuiTreeNodeFlags f=ImGuiTreeNodeFlags_DefaultOpen|ImGuiTreeNodeFlags_OpenOnArrow;if(n->getSubnodes().empty())f|=ImGuiTreeNodeFlags_Leaf;const auto s=n->toString();if(ImGui::TreeNodeEx(n,f,"%s",s.c_str())){for(auto* sn:n->getSubnodes())populateTreeNodes(sn);ImGui::TreePop();}}}
}